[tool.poetry]
name = "bot-starostat-fastapi"
version = "0.1.0"
description = ""
authors = ["Pavel <toruchan174@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
