import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db97ecac1af7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_groups")
    # ### end Alembic commands ###
